import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:pos_app/dtos/operacao-dto-list.dart';
import 'package:pos_app/dtos/operacao-dto.dart';

import '../dtos/operacao-dto-nova.dart';
import '../utilitarios/VariaveisGlobais.dart';

class OperacaoController {
  Future<http.Response> fazRequisicao() async {
    var headers = {
      'idUsuario': '${VariaveisGlobais.usuarioDto.id}',
      'idColaborador': '40eb39abc2f44908ae5dfc16687cc977',
      'Content-Type': 'application/json',
    };
    var body = {
      'nadaAindaDefinidoNoFiltro': true,
    };
    var response = await http.post( Uri.parse('${VariaveisGlobais.endPoint}/operacao/lista'), headers: headers, body: jsonEncode(body),
    );
    return response;
  }

  Future<void> atualizarOperacoes() async {
    http.Response fazRequisicao = await OperacaoController().fazRequisicao();
    if (fazRequisicao.statusCode == 200){
      var result = OperacaoController().buscarProdutoList(fazRequisicao);

      result.then((value) => VariaveisGlobais.operacoesBackEnd = value);


      // buscarProdutoList.then((listaProdutos) {
      //   VariaveisGlobais.autogenerated = listaProdutos.produtosList;
      // }).catchError((erro) {
      //   print(erro);
      // });
    }
  }

  Future<OperacoesDoBackEnd> buscarProdutoList(http.Response response) async {
    Map<String, dynamic> jsonResponse = json.decode(response.body);
    OperacoesDoBackEnd responseModel = OperacoesDoBackEnd.fromJson(jsonResponse);
    return responseModel;
  }

}
