name: pos_app
description: POS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cron: ^0.5.1
  curved_navigation_bar: ^1.0.3
  flutter_local_notifications: ^15.1.0+1
  flutter_keyboard_visibility: ^5.0.0
  google_fonts: ^4.0.4
  http: ^0.13.3
  intl: ^0.17.0
  flutter_hooks: ^0.20.0
  lottie: ^1.0.1
  path_provider: ^2.0.15
  page_transition: ^2.0.4
  pdf: ^3.10.4
  pdf_viewer_plugin: ^2.0.1
  open_file: ^3.1.0
  shared_preferences: ^2.2.0
  share: ^2.0.4
  syncfusion_flutter_charts: ^20.1.60

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
